spring:
  application:
    name: PaymentGatewayInvoiceService

  datasource:
    url: jdbc:mysql://localhost:3306/payment_gw_invoice
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

country:
  allowed: # Add ISO3 codes of the country to avoid mistake
    - ARE
email:
    username: username
    password: password
    enabled: false